/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.sweetop.studyspring.ioc.HelloIoc;
import com.sweetop.studyspring.ioc.SpringLifeCycle;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import javax.servlet.Servlet;

import java.sql.Statement;

import static org.junit.Assert.*;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = {"classpath:spring.xml"})
public class AppTest {
    @Autowired
    private HelloIoc helloIoc;

    @Autowired
    private SpringLifeCycle springLifeCycle;
    @Autowired
    private SpringLifeCycle springLifeCycle2;


    @Test
    public void testIoc() {
        helloIoc.sayHello("world");
    }

    @Test
    public void testLifeCycle() {
         springLifeCycle.sayHello();
         springLifeCycle2.sayHello();

        Statement
    }
}
