/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.sweetop.studymybatis.domain.Role;
import com.sweetop.studymybatis.domain.Subspace;
import com.sweetop.studymybatis.domain.User;
import com.sweetop.studymybatis.mapping.SubspaceMapper1;
import com.sweetop.studymybatis.mapping.UserMapper1;
import com.sweetop.studymybatis.utils.MyBatisUtil;
import org.apache.ibatis.session.SqlSession;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import java.util.List;

import static org.junit.Assert.*;

public class AppTest {
    private static MyBatisUtil myBatisUtil;
    private static String strMappingPre = "com.sweetop.studymybatis.mapping.";

    @BeforeClass
    public static void setUpBeforeClass() throws Exception {
        myBatisUtil = new MyBatisUtil();
    }

    @Test
    public void testGetUser() {
        SqlSession sqlSession = myBatisUtil.getSqlSession();
//        String statement = strMappingPre + "userMapper.getUser";
//        User user = sqlSession.selectOne(statement, 2);
        UserMapper1 mapper = sqlSession.getMapper(UserMapper1.class);
        User user = mapper.getById(2);
        System.out.println(user);
    }

    @Test
    public void testAddUser() {
        SqlSession sqlSession = myBatisUtil.getSqlSession(
                true);
        User user = new User();
        user.setUsername("wudd2");
        user.setUsrPubID("440104000040000000010");

//        String statement = strMappingPre + "userMapper.addUser";
//        int resultCode = sqlSession.insert(statement, user);
        UserMapper1 mapper = sqlSession.getMapper(UserMapper1.class);
        int resultCode = mapper.add(user);
        sqlSession.close();
        System.out.println(resultCode);
    }

    @Test
    public void testUpdateUser() {
        SqlSession sqlSession = myBatisUtil.getSqlSession(true);
        User user = new User();
        user.setId(7);
        user.setUsername("wudd3");
        user.setUsrPubID("44010400004000000010");
//        String statement = strMappingPre + "userMapper.updateUser";
//        int resultCode = sqlSession.update(statement, user);
        UserMapper1 mapper = sqlSession.getMapper(UserMapper1.class);
        int resultCode = mapper.update(user);
        sqlSession.close();
        System.out.println(resultCode);
    }

    @Test
    public void testDeleteUser() {
        SqlSession sqlSession = myBatisUtil.getSqlSession(true);
//        String statement = strMappingPre + "userMapper.deleteUser";
//        int resultCode = sqlSession.delete(statement, 5);
        UserMapper1 mapper = sqlSession.getMapper(UserMapper1.class);
        int resultCode = mapper.deleteById(7);
        sqlSession.close();
        System.out.println(resultCode);
    }

    @Test
    public void testGetAllUsers() {
        SqlSession sqlSession = myBatisUtil.getSqlSession();

        String statement = strMappingPre + "userMapper.getAllUsers";
        List<User> users = sqlSession.selectList(statement);

//        UserMapper1 mapper = sqlSession.getMapper(UserMapper1.class);
//        List<User> users = mapper.getAll();
        users.forEach((user) -> {
                    System.out.println(user);
                }
        );

    }


    @Test
    public void testGetAllUsers2() {
        SqlSession sqlSession = myBatisUtil.getSqlSession();

        String statement = strMappingPre + "userMapper.getAllUsers2";
        List<User> users = sqlSession.selectList(statement);

//        UserMapper1 mapper = sqlSession.getMapper(UserMapper1.class);
//        List<User> users = mapper.getAll();
        users.forEach((user) -> {
                    System.out.println(user);
                }
        );

    }

//    @Test
//    public void testGetRole() {
//        SqlSession sqlSession = myBatisUtil.getSqlSession();
////        String statement = strMappingPre + "userMapper.getUser";
////        User user = sqlSession.selectOne(statement, 2);
//        UserMapper1 mapper = sqlSession.getMapper(UserMapper1.class);
//        Role role = mapper.getRole(1);
//        System.out.println(role);
//    }

    @Test
    public void testGetSubspace() {
        SqlSession sqlSession = myBatisUtil.getSqlSession();
        String statement = strMappingPre + "SubspaceMapper.getSubspace";
        Subspace subspace = sqlSession.selectOne(statement,259);
        System.out.println(subspace);
    }

    @Test
    public void testGetSubspace2() {
        SqlSession sqlSession = myBatisUtil.getSqlSession();
        String statement = strMappingPre + "SubspaceMapper.getSubspace2";
        Subspace subspace = sqlSession.selectOne(statement,259);
        System.out.println(subspace);
    }

    @Test
    public void testGetSubspace3() {
        SqlSession sqlSession = myBatisUtil.getSqlSession();
        SubspaceMapper1 subspaceMapper1=sqlSession.getMapper(SubspaceMapper1.class);
        Subspace subspace=subspaceMapper1.getById(259);
        System.out.println(subspace);
    }

}
