import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private static SessionFactory factory;

    public static void main(String[] args) {
        factory = new Configuration().configure().buildSessionFactory();
    }
}
